# Generated by Django 5.1.6 on 2025-02-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_city_country_alter_airplane_name_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                fields=("source", "destination"), name="unique_route_source_destination"
            ),
        ),
    ]
