# Generated by Django 5.1.6 on 2025-02-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_route_unique_route_source_destination"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="airplane",
            constraint=models.UniqueConstraint(
                fields=("name", "rows", "seats_in_row", "airplane_type"),
                name="unique_airplane",
            ),
        ),
        migrations.AddConstraint(
            model_name="airport",
            constraint=models.UniqueConstraint(
                fields=("name", "closest_big_city"), name="unique_airport"
            ),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                fields=("name", "country"), name="unique_city_country"
            ),
        ),
        migrations.AddConstraint(
            model_name="flight",
            constraint=models.UniqueConstraint(
                fields=("route", "airplane", "departure_time", "arrival_time"),
                name="unique_flight",
            ),
        ),
    ]
