# Generated by Django 5.1.6 on 2025-02-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_airplane_unique_airplane_airport_unique_airport_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ("row", "seat")},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("flight", "row", "seat")},
        ),
    ]
