# Generated by Django 5.1.6 on 2025-03-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0006_alter_ticket_options_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("flight", "row", "seat"), name="unique_ticket"
            ),
        ),
    ]
